# Prometheus Configuration
# Collects metrics from all Jatan services

global:
  scrape_interval: 15s      # Scrape metrics every 15 seconds
  evaluation_interval: 15s   # Evaluate rules every 15 seconds
  external_labels:
    cluster: 'jatan_salary_system'
    environment: 'production'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          service: 'prometheus'

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
        labels:
          service: 'postgresql'
          database: 'labor_salary_db'

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
        labels:
          service: 'redis'
          role: 'cache'

  # RabbitMQ metrics
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq_exporter:9419']
        labels:
          service: 'rabbitmq'
          role: 'message_broker'

  # Celery metrics
  - job_name: 'celery'
    static_configs:
      - targets: ['celery_exporter:9808']
        labels:
          service: 'celery'
          role: 'task_queue'

  # Node exporter (optional - for host metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          service: 'node'
          role: 'host_metrics'

  # cAdvisor (optional - for container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'cadvisor'
          role: 'container_metrics'


