name: Build Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build Windows EXE
      run: |
        python -m PyInstaller build_exe.spec --clean --noconfirm
        
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_OUTPUT
      shell: bash
      
    - name: Create build info file
      run: |
        echo "Build Date: $(date)" > dist/BUILD_INFO.txt
        echo "Commit: ${{ github.sha }}" >> dist/BUILD_INFO.txt
        echo "Branch: ${{ github.ref_name }}" >> dist/BUILD_INFO.txt
      shell: bash
      
    - name: Upload Windows EXE as artifact
      uses: actions/upload-artifact@v4
      with:
        name: JatanSalaryApp-Windows-${{ steps.date.outputs.date }}
        path: |
          dist/JatanSalaryApp.exe
          dist/BUILD_INFO.txt
        retention-days: 30
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/JatanSalaryApp.exe
          dist/BUILD_INFO.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
